<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// @var $block \Magento\Checkout\Block\Cart\Grid

/** @var \Magento\Framework\Escaper $escaper */

?>
<div id="container">
    <div id="subscriptionItems">

        <?php $mergedCells = ($this->helper('Magento\Tax\Helper\Data')->displayCartBothPrices() ? 2 : 1); ?>
        <?= /* @noEscape*/ $block->getChildHtml('form_before'); ?>
        <form action="<?= /* @noEscape */ 
        $block->getUrl('checkout/cart/updatePost'); ?>"
              method="post"
              id="form-validate"
              data-mage-init='{"validation":{}}'
              class="form form-cart">
            <?= /* @noEscape*/ $block->getBlockHtml('formkey'); ?>
            <?php
            $nonSubscriptionItems = [];
            $subscriptionItems = [];
            foreach ($block->getItems() as $key => $_item) { ?>
                <?php if (1 != $_item['is_subscribed']) { ?>
                    <?php $nonSubscriptionItems[$key] = $_item; ?>
                <?php } else { ?>
                    <?php $subscriptionItems[$key] = $_item; ?>
                <?php } ?>
            <?php } ?>

            <div class="resp-tabs-container">
                <!-- Non Subscription Items -->
                <div class="cart table-wrapper<?= /* @noEscape*/ 2 == $mergedCells ? ' detailed' : ''; ?>">
                    <?php if ($block->getPagerHtml()) { ?>
                        <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                             data-attribute="cart-products-toolbar-top"><?= /* @noEscape*/ $block->getPagerHtml(); ?></div>
                    <?php } ?>
                    <table id="shopping-cart-table"
                           class="cart items data table"
                           data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
                        <?php if (0 != sizeof($nonSubscriptionItems)) { ?>
                            <h3><?= $escaper->escapeHtml('Non Subscription Items'); ?></h3>
                            <thead>
                            <tr>
                                <th class="col item" scope="col"><span><?= $escaper->escapeHtml('Item'); ?></span></th>
                                <th class="col price" scope="col"><span><?= $escaper->escapeHtml('Price'); ?></span></th>
                                <th class="col qty" scope="col"><span><?= $escaper->escapeHtml('Qty'); ?></span></th>
                                <th class="col subtotal" scope="col"><span><?= $escaper->escapeHtml('Subtotal'); ?></span></th>
                            </tr>
                            </thead>
                        <?php } ?>
                        <?php foreach ($nonSubscriptionItems as $_item) { ?>
                            <?= /* @noEscape*/ $block->getItemHtml($_item); ?>
                        <?php } ?>
                    </table>
                    <?php if ($block->getPagerHtml()) { ?>
                        <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                             data-attribute="cart-products-toolbar-bottom"><?= /* @noEscape*/ $block->getPagerHtml(); ?></div>
                    <?php } ?>
                </div>


                <!-- Subscription Items -->
                <div class="cart table-wrapper<?= /* @noEscape*/ 2 == $mergedCells ? ' detailed' : ''; ?>">
                    <?php if ($block->getPagerHtml()) { ?>
                        <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                             data-attribute="cart-products-toolbar-top"><?= /* @noEscape*/ $block->getPagerHtml(); ?></div>
                    <?php } ?>
                    <table id="shopping-cart-table"
                           class="cart items data table"
                           data-mage-init='{"shoppingCart":{"emptyCartButton": "action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>
                        <?php if (0 != sizeof($subscriptionItems)) { ?>
                            <h3><?= $escaper->escapeHtml('Subscription Items'); ?></h3>
                            <thead>
                            <tr>
                                <th class="col item" scope="col"><span><?= $escaper->escapeHtml('Item'); ?></span></th>
                                <th class="col price" scope="col"><span><?= $escaper->escapeHtml('Price'); ?></span></th>
                                <th class="col qty" scope="col"><span><?= $escaper->escapeHtml('Qty'); ?></span></th>
                                <th class="col subtotal" scope="col"><span><?= $escaper->escapeHtml('Subtotal'); ?></span></th>
                            </tr>
                            </thead>
                        <?php } ?>
                        <?php foreach ($subscriptionItems as $_item) { ?>
                            <?= /* @noEscape */ $block->getItemHtml($_item); ?>
                        <?php } ?>
                    </table>
                    <?php if ($block->getPagerHtml()) { ?>
                        <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                             data-attribute="cart-products-toolbar-bottom"><?= /* @noEscape */  $block->getPagerHtml(); ?></div>
                    <?php } ?>
                </div>
            </div>
            <div class="cart main actions">
                <?php if ($block->getContinueShoppingUrl()) { ?>
                    <a class="action continue"
                       href="<?= $block->escapeUrl($block->getContinueShoppingUrl()); ?>"
                       title="<?= $escaper->escapeHtml('Continue Shopping'); ?>">
                        <span><?=
                            $escaper->escapeHtml('Continue Shopping'); ?></span>
                    </a>
                <?php } ?>
                <button type="submit"
                        name="update_cart_action"
                        data-cart-empty=""
                        value="empty_cart"
                        title="<?= $escaper->escapeHtml('Clear Shopping Cart'); ?>"
                        class="action clear" id="empty_cart_button">
                    <span><?= $escaper->escapeHtml('Clear Shopping Cart'); ?></span>
                </button>
                <button type="submit"
                        name="update_cart_action"
                        data-cart-item-update=""
                        value="update_qty"
                        title="<?= $escaper->escapeHtml('Update Shopping Cart'); ?>"
                        class="action update">
                    <span><?= $escaper->escapeHtml('Update Shopping Cart'); ?></span>
                </button>
                <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
            </div>
    </div>
</div>
</form>
<?= /* @noEscape */ $block->getChildHtml('checkout.cart.order.actions');?>
<?= /* @noEscape */ $block->getChildHtml('shopping.cart.table.after');?>
