<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Wagento\Subscription\Block\Frontend\Account\SubscriptionView
 */
$subDetails = $block->getSubscriptions();
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$order_id = $this->getRequest()->getParam('order_id');
$getAction = $this->getRequest()->getActionName();

?>
<div class="subscription-info">
    <div class="subscription-order-date">
        <data><?= $block->formatDate($subDetails->getCreatedAt(), \IntlDateFormatter::LONG, false); ?></data>
    </div>

    <div class="subscription-status">
        <span><?= $block->escapeHtml(__($subHelper->getSubscriptionStatus($subDetails->getStatus()))) ?></span>
    </div>

    <?php if ($getAction == 'edit'): ?>
        <?= $block->escapeHtml(__('Note: Any Change in Subscription will affect next run')); ?>
    <?php endif; ?>
</div>

<?php if ($getAction == 'view'): ?>
    <div class="actions-toolbar subscription-order-actions-toolbar">
        <div class="actions">
            <?php if ($subDetails->getStatus() == 2): ?>
                <a class="order-status" href="<?= $block->getReactivateUrl($order_id); ?>">
                    <?= $block->escapeHtml(__('Reactivate')) ?>
                </a>
            <?php endif; ?>
            <?php if (($subHelper->getCanCustomerCancel() && $subDetails->getStatus() == 1) || $subDetails->getStatus() == 2) : ?>
                <a class="order-status" href="#" id="cancel_status">
                    <?= $block->escapeHtml(__('Cancel')); ?>
                </a>
            <?php endif; ?>

            <?php if ($subHelper->getCanCustomerPause() && $subDetails->getStatus() == 1): ?>
                <a class="order-status" href="<?= $block->getPauseUrl($order_id); ?>">
                    <?= $block->escapeHtml(__('Pause')); ?>
                </a>
            <?php endif; ?>

            <?php if ($subDetails->getStatus() != 0): ?>
                <?php if ($subDetails->getStatus() != 3): ?>
                    <a class="order-status" href="<?= $block->getEditUrl($order_id); ?>">
                        <?= $block->escapeHtml(__('Edit')); ?>
                    </a>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

<form data-mage-init='{"validation": {}}'
      action="<?= $block->getUpdateUrl($order_id); ?>"
      method="post"
      id="form-validate"
      class="form form-subscription-edit">
    <div class="order-details-items">
        <div class="col2-set sub-info-box">
            <div class="col-1-sub">
                <div class="info-box">
                    <div class="box-title">
                        <h2><?= $block->escapeHtml(__('Subscription Profile')); ?></h2>
                    </div>
                    <div class="box-content">
                        <table class="info-table">
                            <tbody>
                            <tr>
                                <th><?= $block->escapeHtml(__('Subscription Plan name')) ?></th>
                                <td><?= $block->escapeHtml($subDetails->getSubName()) ?></td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Subscription Frequency')); ?> </th>
                                <td>
                                    <?= $block->escapeHtml($subHelper->getSubscriptionFrequency($subDetails->getSubFrequency())) ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Subscription Cycle')); ?></th>
                                <td>
                                    <?php if ($subDetails->getHowMany() != NULL): ?>
                                        <?= $subDetails->getHowMany() ?>
                                        <?= $block->escapeHtml($subHelper->getHowManyUnits($subDetails->getFrequency())) ?>
                                    <?php else: ?>
                                        <?= $block->escapeHtml(__('N/A')); ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Subscription Billing Count')); ?></th>
                                <td>
                                    <?php $billingCount = $subDetails->getBillingCount();
                                    if (isset($billingCount)): ?>
                                        <?= $block->escapeHtml($subDetails->getBillingCount()); ?>
                                        <?= $block->escapeHtml(__('- Times Billed')); ?>
                                    <?php else: ?>
                                        <?= $block->escapeHtml(__('0 - Times Billed')); ?>
                                    <?php endif; ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Subscription Started Date')) ?></th>
                                <td>
                                    <?php $dt_str = $subDetails->getSubStartDate(); $date   = new Datetime($dt_str); echo $date->format('m/d/y'); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Last Renewed')) ?></th>
                                <td>
                                    <?php $dt_str = $subDetails->getLastRenewed(); $date   = new Datetime($dt_str); echo $date->format('m/d/y'); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?= $block->escapeHtml(__('Next Renewal')) ?></th>
                                <td>
                                    <?php $dt_str = $subDetails->getNextRenewed(); $date   = new Datetime($dt_str); echo $date->format('m/d/y'); ?>

                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-2-sub">
                <div class="info-box">
                    <div class="box-title">
                        <h2><?= $block->escapeHtml(__('Subscription Item Details')); ?></h2>
                    </div>
                </div>
                <div class="box-content">
                    <table>
                        <tbody>
                        <tr>
                            <th><?= $block->escapeHtml(__('Product Name')) ?></th>
                            <td><?= $block->escapeHtml($subDetails->getName()) ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('SKU')); ?> </th>
                            <td><?= $subDetails->getSku() ?></td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Quantity')); ?> </th>
                            <td>
                                <?= $block->escapeHtml((int)$subDetails->getQtyOrdered()) ?>
                                <?= $block->escapeHtml(__('Subscribed')) ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Price')) ?></th>
                            <td>
                                <strong>
                                    <?= $priceHelper->currency(number_format($subDetails->getPrice(), 2), true, false) ?>
                                </strong>
                            </td>
                        </tr>
                        <tr>
                            <th><?= $block->escapeHtml(__('Initial Fee')) ?></th>
                            <td>
                                <strong>
                                    <?= $priceHelper->currency(number_format($subDetails->getSubFee(), 2), true, false) ?>
                                </strong>
                            </td>
                        </tr>
                        <tr>
                            <?php $paymentDetail = $block->getPaymentMethod($subDetails->getOrderId(), $subDetails->getPublicHash(), $subDetails->getCustomerId()); ?>
                            <th class="card_detail"><?= $block->escapeHtml(__('Card Details')) ?></th>
                            <?php if ($getAction == 'view') : ?>
                                <?php if (isset($paymentDetail['cc_number'])): ?>
                                    <td><?= $paymentDetail['cc_number'] ?></td>
                                <?php else: ?>
                                    <td><?= $block->escapeHtml(__('N/A')) ?></td>
                                <?php endif; ?>
                            <?php elseif ($getAction == 'edit'): ?>
                                <?php $cardCollection = $subHelper->getCardCollection($subDetails->getCustomerId()); ?>
                                <?php $selected = ''; ?>
                                <td><select name="subscription-card" data-validate="{required:true}">
                                        <?= $block->escapeHtml(__('Card Details')) ?>
                                        <option value=""><?= $block->escapeHtml(__('Select Card')) ?></option>
                                        <?php if (!empty($cardCollection)) : ?>
                                            <?php foreach ($cardCollection as $key => $cc): ?>
                                                <?php if (isset($paymentDetail['cc_number'])): ?>
                                                    <?php if ($paymentDetail['cc_number'] == $cc['label']) {
                                                        $selected = 'selected';
                                                    } else {
                                                        $selected = '';
                                                    } ?>
                                                <?php endif; ?>
                                                <option value="<?= $cc['value'] ?>" <?= $selected ?>><?= $cc['label'] ?></option>
                                            <?php endforeach; ?>
                                        <?php endif; ?>
                                    </select></td>
                            <?php endif; ?>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <div class="order-details-items">
        <div class="block block-order-details-view">
            <div class="block-title">
                <h2><?= $block->escapeHtml(__('Subscription Address Information')) ?></h2>
            </div>
            <div class="block-content">
                <div class="box box-order-shipping-address">
                    <?php /* Shipping Address */ ?>
                    <div class="info-box">
                        <div class="box-title"><h3><?= $block->escapeHtml(__('Shipping Address')); ?></h3></div>
                            <?php if ($getAction == 'view') : ?>
                                <address>
                                    <?php $shippingAddress = $block->getShippingAddress($subDetails->getOrderId()) ?>
                                    <?php if(empty($shippingAddress)) : ?>
                                        <?= $block->escapeHtml(__('N/A')) ?>
                                    <?php else: ?>
                                        <?=  $block->getShippingAddress($subDetails->getOrderId()); ?>
                                    <?php ?>
                                </address>
                            <?php endif;?>
                        <?php elseif ($getAction == 'edit'): ?>
                            <?php if($subDetails->getProductType()=='downloadable') : ?>
                                <br/><?= $block->escapeHtml(__('N/A')) ?>
                            <?php else: ?>
                                <select name="subscription-shipping">
                                    <option value=""><?= $block->escapeHtml(__('Select Shipping Address')) ?></option>
                                    <?php
                                    $addresses = $block->getCustomerAddressInline();
                                    $subShippingId = $subDetails->getShippingAddressId();
                                    $orderAddress = null;
                                    $orderAddressValue = $subDetails->getOrderShippingAddress();
                                    if (isset($orderAddressValue)) {
                                        $orderAddress = $subHelper->getSelectedId($subDetails->getOrderShippingAddress());
                                    }
                                    ?>
                                    <?php if (!empty($addresses)): ?>
                                        <?php foreach ($addresses as $key => $address): ?>
                                            <?php
                                            $selected = '';
                                            if (isset($subShippingId) && $subShippingId == $address['value']) {
                                                $selected = 'selected';
                                            } else if (isset($orderAddress) && $orderAddress == $address['value']) {
                                                $selected = 'selected';
                                            }
                                            ?>
                                            <option value="<?= $address['value'] ?>" <?= $selected ?>><?= $address['label'] ?></option>
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </select>
                                <?php endif;?>
                            <?php endif; ?>
                    </div>
                </div>

                <?php if ($getAction == 'view') : ?>
                    <div class="box box-order-shipping-method">
                        <?php $shippingMethod = $block->getShippingMethod($subDetails->getOrderId()) ?>
                        <div class="info-box">
                            <div class="box-title"><h3><?= $block->escapeHtml(__('Shipping Method')); ?></h3></div>
                        </div>
                        <address>
                            <?php if(empty($shippingMethod)) : ?>
                                <?= $block->escapeHtml(__('N/A')) ?>
                            <?php else :?>
                                <?= /* @noEscape */ $block->getShippingMethod($subDetails->getOrderId()) ?>
                            <?php endif; ?>
                        </address>
                    </div>
                <?php endif; ?>


                <div class="box box-order-billing-address">
                    <?php /* Billing Address */ ?>
                    <div class="info-box">
                        <div class="box-title"><h3><?= $block->escapeHtml(__('Billing Address')); ?></h3></div>
                        <?php if ($getAction == 'view') : ?>
                            <address><?= /* @noEscape */
                                $block->getBillingAddress($subDetails->getOrderId()) ?></address>
                        <?php elseif ($getAction == 'edit'): ?>
                            <select name="subscription-billing" data-validate="{required:true}">
                                <option value=""><?= $block->escapeHtml(__('Select Billing Address')) ?></option>
                                <?php
                                $addresses = $block->getCustomerAddressInline();
                                $subBillingId = $subDetails->getBillingAddressId();
                                $orderAddressBill = $subHelper->getSelectedId($subDetails->getOrderBillingAddress());
                                $orderAddressShip = $subDetails->getOrderShippingAddress();
                                if (isset($orderAddressShip)) {
                                    $orderAddressShip = $subHelper->getSelectedId($subDetails->getOrderShippingAddress());
                                }
                                ?>
                                <?php foreach ($addresses as $key => $address): ?>
                                    <?php
                                    $selected = '';
                                    if (isset($subBillingId) && $subBillingId == $address['value']) {
                                        $selected = 'selected';
                                    } else if ($orderAddressBill == $address['value']) {
                                        $selected = 'selected';
                                    } else if ($orderAddressShip == $address['value']) {
                                        $selected = 'selected';
                                    }
                                    ?>
                                    <option value="<?= $address['value'] ?>" <?= $selected ?>><?= $address['label'] ?></option>
                                <?php endforeach; ?>
                                <!--                                --><?php //endif; ?>
                            </select>
                        <?php endif; ?>
                    </div>
                </div>

                <?php if ($getAction == 'view') : ?>
                    <div class="box box-order-billing-method">
                        <?php /* Billing Method */ ?>
                        <div class="info-box">
                            <div class="box-title"><h3><?= $block->escapeHtml(__('Payment Method')); ?></h3></div>
                        </div>
                        <?php $paymentDetail = $block->getPaymentMethod($subDetails->getOrderId(), $subDetails->getPublicHash(), $subDetails->getCustomerId()); ?>
                        <div class="box-content">
                            <dl class="payment-method">
                                <p><?= $paymentDetail['method_title'] ?></p>
                                <?php if (isset($paymentDetail['cc_type'])): ?>
                                    <dd class="content">
                                        <table class="data table">
                                            <tbody>
                                            <tr>
                                                <th scope="row"><?= $block->escapeHtml(__('Credit Card Type')); ?></th>
                                                <td><?= $paymentDetail['cc_type'] ?></td>
                                            </tr>
                                            <tr>
                                                <th scope="row"><?= $block->escapeHtml(__('Credit Card Number')); ?></th>
                                                <td><?= $paymentDetail['cc_number'] ?></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </dd>
                                <?php endif; ?>
                            </dl>
                        </div>
                    </div>
                <?php endif; ?>

                <?php if ($getAction == 'edit') : ?>
                    <div class="box-content edit-subscription">
                        <button type="submit"><span><?= $block->escapeHtml(__('Update Subscription')); ?></span>
                        </button>
                    </div>
                <?php endif; ?>
            </div>
        </div>
</form>
<?php if ($subDetails['how_many'] == NULL): ?>
    <div class="order-details-note">
        <div class="block block-subscription-details-view">
            <div class="block-title">
                <h2><?= $block->escapeHtml(__('Subscription Note')) ?></h2>
            </div>
            <div class="block-content">
                <th><?= $block->escapeHtml(__('You can stop subscription at any time by pausing or cancelling the subscription')) ?></th>
            </div>
        </div>
    </div>
<?php endif; ?>
</div>


<script>
    require([
        "jquery"
    ], function ($) {
        $("#cancel_status").click(function () {
            if (confirm("Are you sure want to cancel this subscription?")) {
                $(location).attr('href', "<?= $block->getCancelUrl($order_id); ?>");
            }
        })
    });
</script>
