<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var \Wagento\Subscription\Block\Frontend\Account\SubscriptionView $block
 */
$subDetails = $block->getSubscriptions();
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$order_id = $this->getRequest()->getParam('order_id');
$getAction = $this->getRequest()->getActionName();

?>
<div class="subscription-info">
    <div class="subscription-order-date">
        <data><?php echo $block->formatDate($subDetails->getCreatedAt(), \IntlDateFormatter::LONG, false); ?></data>
    </div>

    <div class="subscription-status">
        <span><?php echo $block->escapeHtml(__($subHelper->getSubscriptionStatus($subDetails->getStatus()))); ?></span>
    </div>

    <?php if ('edit' == $getAction) { ?>
        <?php echo $block->escapeHtml(__('Note: Any Change in Subscription will affect next run')); ?>
    <?php } ?>
</div>

<?php if ('view' == $getAction) { ?>
    <div class="actions-toolbar subscription-order-actions-toolbar">
        <div class="actions">
            <?php if (2 == $subDetails->getStatus()) { ?>
                <a class="order-status" href="<?php echo $block->getReactivateUrl($order_id); ?>">
                    <?php echo $block->escapeHtml(__('Reactivate')); ?>
                </a>
            <?php } ?>
            <?php if (($subHelper->getCanCustomerCancel() && 1 == $subDetails->getStatus()) || 2 == $subDetails->getStatus()) { ?>
                <a class="order-status" href="#" id="cancel_status">
                    <?php echo $block->escapeHtml(__('Cancel')); ?>
                </a>
            <?php } ?>

            <?php if ($subHelper->getCanCustomerPause() && 1 == $subDetails->getStatus()) { ?>
                <a class="order-status" href="<?php echo $block->getPauseUrl($order_id); ?>">
                    <?php echo $block->escapeHtml(__('Pause')); ?>
                </a>
            <?php } ?>

            <?php if (0 != $subDetails->getStatus()) { ?>
                <?php if (3 != $subDetails->getStatus()) { ?>
                    <a class="order-status" href="<?php echo $block->getEditUrl($order_id); ?>">
                        <?php echo $block->escapeHtml(__('Edit')); ?>
                    </a>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>

<form data-mage-init='{"validation": {}}'
      action="<?php echo $block->getUpdateUrl($order_id); ?>"
      method="post"
      id="form-validate"
      class="form form-subscription-edit">
    <div class="order-details-items">
        <div class="col2-set sub-info-box">
            <div class="col-1-sub">
                <div class="info-box">
                    <div class="box-title">
                        <h2><?php echo $block->escapeHtml(__('Subscription Profile')); ?></h2>
                    </div>
                    <div class="box-content">
                        <table class="info-table">
                            <tbody>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Subscription Plan name')); ?></th>
                                <td><?php echo $block->escapeHtml($subDetails->getSubName()); ?></td>
                            </tr>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Subscription Frequency')); ?> </th>
                                <td>
                                    <?php echo $block->escapeHtml($subHelper->getSubscriptionFrequency($subDetails->getSubFrequency())); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Subscription Cycle')); ?></th>
                                <td>
                                    <?php if (null != $subDetails->getHowMany()) { ?>
                                        <?php echo $subDetails->getHowMany(); ?>
                                        <?php echo $block->escapeHtml($subHelper->getHowManyUnits($subDetails->getFrequency())); ?>
                                    <?php } else { ?>
                                        <?php echo $block->escapeHtml(__('N/A')); ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Subscription Billing Count')); ?></th>
                                <td>
                                    <?php $billingCount = $subDetails->getBillingCount();
                                    if (isset($billingCount)) { ?>
                                        <?php echo $block->escapeHtml($subDetails->getBillingCount()); ?>
                                        <?php echo $block->escapeHtml(__('- Times Billed')); ?>
                                    <?php } else { ?>
                                        <?php echo $block->escapeHtml(__('0 - Times Billed')); ?>
                                    <?php } ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Subscription Started Date')); ?></th>
                                <td>
                                    <?php $dt_str = $subDetails->getSubStartDate(); $date = new DateTime($dt_str); echo $date->format('F d, Y'); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Last Renewed')); ?></th>
                                <td>
                                    <?php $dt_str = $subDetails->getLastRenewed(); $date = new DateTime($dt_str); echo $date->format('F d, Y'); ?>
                                </td>
                            </tr>
                            <tr>
                                <th><?php echo $block->escapeHtml(__('Next Renewal')); ?></th>
                                <td>
                                    <?php $dt_str = $subDetails->getNextRenewed(); $date = new DateTime($dt_str); echo $date->format('F d, Y'); ?>

                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="col-2-sub">
                <div class="info-box">
                    <div class="box-title">
                        <h2><?php echo $block->escapeHtml(__('Subscription Item Details')); ?></h2>
                    </div>
                </div>
                <div class="box-content">
                    <table>
                        <tbody>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Product Name')); ?></th>
                            <td><?php echo $block->escapeHtml($subDetails->getName()); ?></td>
                        </tr>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('SKU')); ?> </th>
                            <td><?php echo $subDetails->getSku(); ?></td>
                        </tr>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Quantity')); ?> </th>
                            <td>
                                <?php echo $block->escapeHtml((int) $subDetails->getQtyOrdered()); ?>
                                <?php echo $block->escapeHtml(__('Subscribed')); ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Price')); ?></th>
                            <td>
                                <strong>
                                    <?php echo $priceHelper->currency(number_format($subDetails->getPrice(), 2), true, false); ?>
                                </strong>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Initial Fee')); ?></th>
                            <td>
                                <strong>
                                    <?php echo $priceHelper->currency(number_format($subDetails->getSubFee(), 2), true, false); ?>
                                </strong>
                            </td>
                        </tr>
                        <tr>
                            <?php $paymentDetail = $block->getPaymentMethod($subDetails->getOrderId(), $subDetails->getPublicHash(), $subDetails->getCustomerId()); ?>
                            <th class="card_detail"><?php echo $block->escapeHtml(__('Card Details')); ?></th>
                            <?php if ('view' == $getAction) { ?>
                                <?php if (isset($paymentDetail['cc_number'])) { ?>
                                    <td><?php echo $paymentDetail['cc_number']; ?></td>
                                <?php } else { ?>
                                    <td><?php echo $block->escapeHtml(__('N/A')); ?></td>
                                <?php } ?>
                            <?php } elseif ('edit' == $getAction) { ?>
                                <?php $cardCollection = $subHelper->getCardCollection($subDetails->getCustomerId()); ?>
                                <?php $selected = ''; ?>
                                <td><select name="subscription-card" data-validate="{required:true}">
                                        <?php echo $block->escapeHtml(__('Card Details')); ?>
                                        <option value=""><?php echo $block->escapeHtml(__('Select Card')); ?></option>
                                        <?php if (!empty($cardCollection)) { ?>
                                            <?php foreach ($cardCollection as $key => $cc) { ?>
                                                <?php if (isset($paymentDetail['cc_number'])) { ?>
                                                    <?php if ($paymentDetail['cc_number'] == $cc['label']) {
                                        $selected = 'selected';
                                    } else {
                                        $selected = '';
                                    } ?>
                                                <?php } ?>
                                                <option value="<?php echo $cc['value']; ?>" <?php echo $selected; ?>><?php echo $cc['label']; ?></option>
                                            <?php } ?>
                                        <?php } ?>
                                    </select></td>
                            <?php } ?>
                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


    <div class="order-details-items">
        <div class="block block-order-details-view">
            <div class="block-title">
                <h2><?php echo $block->escapeHtml(__('Subscription Address Information')); ?></h2>
            </div>
            <div class="block-content">
                <div class="box box-order-shipping-address">
                    <?php /* Shipping Address */ ?>
                    <div class="info-box">
                        <div class="box-title"><h3><?php echo $block->escapeHtml(__('Shipping Address')); ?></h3></div>
                            <?php if ('view' == $getAction) { ?>
                                <address>
                                    <?php $shippingAddress = $block->getShippingAddress($subDetails->getOrderId()); ?>
                                    <?php if (empty($shippingAddress)) { ?>
                                        <?php echo $block->escapeHtml(__('N/A')); ?>
                                    <?php } else { ?>
                                        <?php echo $block->getShippingAddress($subDetails->getOrderId()); ?>
                                    <?php ?>
                                </address>
                            <?php }?>
                        <?php } elseif ('edit' == $getAction) { ?>
                            <?php if ('downloadable' == $subDetails->getProductType()) { ?>
                                <br/><?php echo $block->escapeHtml(__('N/A')); ?>
                            <?php } else { ?>
                                <select name="subscription-shipping">
                                    <option value=""><?php echo $block->escapeHtml(__('Select Shipping Address')); ?></option>
                                    <?php
                                    $addresses = $block->getCustomerAddressInline();
                                    $subShippingId = $subDetails->getShippingAddressId();
                                    $orderAddress = null;
                                    $orderAddressValue = $subDetails->getOrderShippingAddress();
                                    if (isset($orderAddressValue)) {
                                        $orderAddress = $subHelper->getSelectedId($subDetails->getOrderShippingAddress());
                                    }
                                    ?>
                                    <?php if (!empty($addresses)) { ?>
                                        <?php foreach ($addresses as $key => $address) { ?>
                                            <?php
                                            $selected = '';
                                            if (isset($subShippingId) && $subShippingId == $address['value']) {
                                                $selected = 'selected';
                                            } elseif (isset($orderAddress) && $orderAddress == $address['value']) {
                                                $selected = 'selected';
                                            }
                                            ?>
                                            <option value="<?php echo $address['value']; ?>" <?php echo $selected; ?>><?php echo $address['label']; ?></option>
                                        <?php } ?>
                                    <?php } ?>
                                </select>
                                <?php }?>
                            <?php } ?>
                    </div>
                </div>

                <?php if ('view' == $getAction) { ?>
                    <div class="box box-order-shipping-method">
                        <?php $shippingMethod = $block->getShippingMethod($subDetails->getOrderId()); ?>
                        <div class="info-box">
                            <div class="box-title"><h3><?php echo $block->escapeHtml(__('Shipping Method')); ?></h3></div>
                        </div>
                        <address>
                            <?php if (empty($shippingMethod)) { ?>
                                <?php echo $block->escapeHtml(__('N/A')); ?>
                            <?php } else { ?>
                                <?php echo /* @noEscape */ $block->getShippingMethod($subDetails->getOrderId()); ?>
                            <?php } ?>
                        </address>
                    </div>
                <?php } ?>


                <div class="box box-order-billing-address">
                    <?php /* Billing Address */ ?>
                    <div class="info-box">
                        <div class="box-title"><h3><?php echo $block->escapeHtml(__('Billing Address')); ?></h3></div>
                        <?php if ('view' == $getAction) { ?>
                            <address><?php echo // @noEscape
                                $block->getBillingAddress($subDetails->getOrderId()); ?></address>
                        <?php } elseif ('edit' == $getAction) { ?>
                            <select name="subscription-billing" data-validate="{required:true}">
                                <option value=""><?php echo $block->escapeHtml(__('Select Billing Address')); ?></option>
                                <?php
                                $addresses = $block->getCustomerAddressInline();
                                $subBillingId = $subDetails->getBillingAddressId();
                                $orderAddressBill = $subHelper->getSelectedId($subDetails->getOrderBillingAddress());
                                $orderAddressShip = $subDetails->getOrderShippingAddress();
                                if (isset($orderAddressShip)) {
                                    $orderAddressShip = $subHelper->getSelectedId($subDetails->getOrderShippingAddress());
                                }
                                ?>
                                <?php foreach ($addresses as $key => $address) { ?>
                                    <?php
                                    $selected = '';
                                    if (isset($subBillingId) && $subBillingId == $address['value']) {
                                        $selected = 'selected';
                                    } elseif ($orderAddressBill == $address['value']) {
                                        $selected = 'selected';
                                    } elseif ($orderAddressShip == $address['value']) {
                                        $selected = 'selected';
                                    }
                                    ?>
                                    <option value="<?php echo $address['value']; ?>" <?php echo $selected; ?>><?php echo $address['label']; ?></option>
                                <?php } ?>
                                <!--                                --><?php // endif;?>
                            </select>
                        <?php } ?>
                    </div>
                </div>

                <?php if ('view' == $getAction) { ?>
                    <div class="box box-order-billing-method">
                        <?php /* Billing Method */ ?>
                        <div class="info-box">
                            <div class="box-title"><h3><?php echo $block->escapeHtml(__('Payment Method')); ?></h3></div>
                        </div>
                        <?php $paymentDetail = $block->getPaymentMethod($subDetails->getOrderId(), $subDetails->getPublicHash(), $subDetails->getCustomerId()); ?>
                        <div class="box-content">
                            <dl class="payment-method">
                                <p><?php echo $paymentDetail['method_title']; ?></p>
                                <?php if (isset($paymentDetail['cc_type'])) { ?>
                                    <dd class="content">
                                        <table class="data table">
                                            <tbody>
                                            <tr>
                                                <th scope="row"><?php echo $block->escapeHtml(__('Credit Card Type')); ?></th>
                                                <td><?php echo $paymentDetail['cc_type']; ?></td>
                                            </tr>
                                            <tr>
                                                <th scope="row"><?php echo $block->escapeHtml(__('Credit Card Number')); ?></th>
                                                <td><?php echo $paymentDetail['cc_number']; ?></td>
                                            </tr>
                                            </tbody>
                                        </table>
                                    </dd>
                                <?php } ?>
                            </dl>
                        </div>
                    </div>
                <?php } ?>

                <?php if ('edit' == $getAction) { ?>
                    <div class="box-content edit-subscription">
                        <button type="submit"><span><?php echo $block->escapeHtml(__('Update Subscription')); ?></span>
                        </button>
                    </div>
                <?php } ?>
            </div>
        </div>
</form>
<?php if (null == $subDetails['how_many']) { ?>
    <div class="order-details-note">
        <div class="block block-subscription-details-view">
            <div class="block-title">
                <h2><?php echo $block->escapeHtml(__('Subscription Note')); ?></h2>
            </div>
            <div class="block-content">
                <th><?php echo $block->escapeHtml(__('You can stop subscription at any time by pausing or cancelling the subscription')); ?></th>
            </div>
        </div>
    </div>
<?php } ?>
</div>


<script>
    require([
        "jquery"
    ], function ($) {
        $("#cancel_status").click(function () {
            if (confirm("Are you sure want to cancel this subscription?")) {
                $(location).attr('href', "<?php echo $block->getCancelUrl($order_id); ?>");
            }
        })
    });
</script>
