<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile
// @var \Wagento\Subscription\Block\Frontend\Account\SubscriptionOrder $block

/** @var \Magento\Framework\Escaper $escaper */
?>

<?php
$subscriptions = $block->getSubscriptions();
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
?>
<?php if (count($subscriptions) > 0) { ?>
    <div class="table-wrapper seller-product">
        <table class="data table table-seller-items" id="my-seller-products">
            <caption class="table-caption"><?= $ecaper->escapeHtml('My Subscriptions'); ?></caption>
            <thead>

            <th scope="col" class="col profile"><?= $ecaper->escapeHtml('Profile #'); ?></th>
            <th scope="col" class="col date"><?= $ecaper->escapeHtml('Purchase Date'); ?></th>
            <th scope="col" class="col next-renew"><?= $ecaper->escapeHtml('Next Renewal Date'); ?></th>
            <th scope="col" class="col last-renew"><?= $ecaper->escapeHtml('Last Renewed Date'); ?></th>
            <th scope="col" class="col shipping"><?= $ecaper->escapeHtml('Ship To'); ?></th>
            <th scope="col" class="col total"><?= $ecaper->escapeHtml('Price'); ?></th>
            <th scope="col" class="col status"><?= $ecaper->escapeHtml('Status'); ?></th>
            <th scope="col" class="col action"><?= $ecaper->escapeHtml('Action'); ?></th>
            </thead>
            <tbody>
            <?php foreach ($subscriptions as $key => $subscription) { ?>
                <tr>
                    <td data-th="<?= $ecaper->escapeHtml('Subscription Profile #'); ?>" class="col name">
                        <?= $ecaper->escapeHtml($subscription->getId()); ?>
                    </td>
                    <td data-th="<?= $ecaper->escapeHtml('Purchase Date'); ?>" class="col date">
                        <?php $dt_str = $subscription->getCreatedAt(); $date = new DateTime($dt_str); ?> 
                        <?= /* @noEscape */ $date->format('m/d/y'); ?>
                    </td>
                    <td data-th="<?= $ecaper->escapeHtml('Next Renewal Date'); ?>" class="col date">
                        <?php $dt_str = $subscription->getNextRenewed(); $date = new DateTime($dt_str); ?> 
                        <?= /* @noEscape*/ $date->format('m/d/y'); ?>
                    </td>

                    <td data-th="<?= $ecaper->escapeHtml('Last Renewed Date'); ?>" class="col date">
                        <?php $dt_str = $subscription->getLastRenewed(); $date = new DateTime($dt_str); ?> 
                        <?= /* @noEscape*/  $date->format('m/d/y'); ?>
                    </td>
                    <td data-th="<?= $ecaper->escapeHtml('Ship To'); ?>" class="col shipping">
                        <?=  $escper->escapeHtml($subscription->getCustomerName()); ?>
                    </td>
                    <td data-th="<?= $ecaper->escapeHtml('Order Total'); ?>" class="col total">
                        <?= /* @noEscape*/ $priceHelper->currency($subscription->getPrice(), 1, 1); ?>
                    </td>
                    <td data-th="<?= $ecaper->escapeHtml('Subscription Status'); ?>" class="col status">
                        <?= /* @noEscape */ $subHelper->getSubscriptionStatus($subscription->getStatus()); ?>
                    </td>
                    <td data-th="<?= $ecaper->escapeHtml('Action'); ?>" class="col action">
                        <a href="<?= /* @noEscape */ $block->getUrl(
                            'subscription/order/view/',
                            ['order_id' => $subscription->getId()]
                        ); ?>">
                        <?= $ecaper->escapeHtml('View Subscription'); ?>
                        </a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>

    <?php if ($block->getPagerHtml()) { ?>
        <div class="order-products-toolbar toolbar bottom">
            <?= /* @noEscape */ $block->getPagerHtml(); ?>
        </div>
    <?php } ?>
<?php } else { ?>
    <div class="table-wrapper seller-product">
        <p><?= $ecaper->escapeHtml('You have no subscription profiles'); ?></p>
    </div>
<?php } ?>
