<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit
/** @var \Magento\Framework\Escaper $escaper */

?>
<?php $isSubscribed = $block->getItem()->getIsSubscribed(); ?>
<?php if (!$isSubscribed): ?>
    <?php if ($block->isProductVisibleInSiteVisibility()) { ?>
        <a class="action action-edit"
           href="<?= /* @noEscape */ $block->getConfigureUrl(); ?>"
           title="<?= $escaper->escapeHtml('Edit item parameters'); ?>">
            <span>
                <?= $escaper->escapeHtml('Edit'); ?>
            </span>
        </a>
    <?php } ?>
<?php endif; ?>
