<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Edit
?>
<?php
$isSubscribed = $block->getItem()->getIsSubscribed();
if (!$isSubscribed) {
    ?>
<?php if ($block->isProductVisibleInSiteVisibility()) { ?>
    <a class="action action-edit"
       href="<?php echo /* @escapeNotVerified */ $block->getConfigureUrl(); ?>"
       title="<?php echo $block->escapeHtml(__('Edit item parameters')); ?>">
        <span>
            <?php echo /* @escapeNotVerified */ __('Edit'); ?>
        </span>
    </a>
<?php } ?>
<?php
} ?>
