<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove
?>
<?php
$isSubscribed = $block->getItem()->getIsSubscribed();
if (!$isSubscribed) {
    ?>
<a href="#"
   title="<?php echo $block->escapeHtml(__('Remove item')); ?>"
   class="action action-delete"
   data-post='<?php echo /* @escapeNotVerified */ $block->getDeletePostJson(); ?>'>
    <span>
        <?php echo /* @escapeNotVerified */ __('Remove item'); ?>
    </span>
</a>
<?php
} ?>