<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove */
?>
<?php
$isSubscribed = $block->getItem()->getIsSubscribed();
if(!$isSubscribed):
?>
<a href="#"
   title="<?= $block->escapeHtml(__('Remove item')) ?>"
   class="action action-delete"
   data-post='<?= /* @escapeNotVerified */ $block->getDeletePostJson() ?>'>
    <span>
        <?= /* @escapeNotVerified */ __('Remove item') ?>
    </span>
</a>
<?php endif ?>