<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// @var $block \Magento\Checkout\Block\Cart\Item\Renderer\Actions\Remove
/** @var \Magento\Framework\Escaper $escaper */

?>
<?php $isSubscribed = $block->getItem()->getIsSubscribed();?>
<?php if (!$isSubscribed): ?>
    <a href="#"
       title="<?= $escaper->escapeHtml('Remove item'); ?>"
       class="action action-delete"
       data-post='<?= /* @noEscape */ $block->getDeletePostJson(); ?>'>
        <span>
            <?= $escaper->escapeHtml('Remove item'); ?>
        </span>
    </a>
<?php endif; ?>