<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Framework\Escaper $escaper */

$productId = $this->getData('productId');
$subHelperLinks = $this->helper('Wagento\Subscription\Helper\Product');
?>
<?php $_linksPurchasedSeparately = $block->getLinksPurchasedSeparately($productId); ?>
<?php if ($subHelperLinks->getProduct($productId)->isSaleable() && $block->hasLinks($productId)) { ?>
    <?php $_links = $block->getLinks($productId); ?>
    <?php $_linksLength = 0; ?>
    <?php $_isRequired = $block->getLinkSelectionRequired($productId); ?>
    <legend class="legend links-title"><span><?= /* @noEscape */ 
            $block->getLinksTitle($productId); ?></span></legend><br>
    <div class="field downloads<?php if ($_isRequired) {
                echo ' required';
            } ?><?php if (!$_linksPurchasedSeparately) {
                echo ' downloads-no-separately';
            } ?>">
        <label class="label"><span><?= /* @noEscape */ 
                $block->getLinksTitle($productId); ?></span></label>
        <div class="control" id="downloadable-links-list"
             data-mage-init='{"downloadable":{
                 "linkElement":"input:checkbox[value]",
                 "allElements":"#links_all",
                 "config":<?= /* @noEscape */ 
             $block->getJsonConfig1($productId); ?>}
             }'
             data-container-for="downloadable-links">
            <?php foreach ($_links as $_link) { ?>
                <?php ++$_linksLength; ?>
                <div class="field choice" data-role="link">
                    <?php if ($_linksPurchasedSeparately) { ?>
                        <input type="checkbox"
                               <?php if ($_isRequired) { ?>data-validate="{'validate-one-checkbox-required-by-name':'downloadable-links-list'}" <?php } ?>
                               name="links[]"
                               id="links_<?= /* @noEscape */ 
                               $_link->getId(); ?>"
                               value="<?= /* @noEscape */ 
                               $_link->getId(); ?>" <?= /* @noEscape */ 
                        $block->getLinkCheckedValue($_link, $productId); ?> />
                    <?php } ?>
                    <label class="label" for="links_<?= /* @noEscape */  
                    $_link->getId(); ?>">
                        <span><?= $escaper->escapeHtml($_link->getTitle()); ?></span>
                        <?php if ($_link->getSampleFile() || $_link->getSampleUrl()) { ?>
                            <a class="sample link"
                               href="<?= // @noEscape
                               $block->getLinkSampleUrl($_link, $productId); ?>" <?= /* @noEscape */ $block->getIsOpenInNewWindow() ? 'target="_blank"' : ''; ?>>
                                <?= $escaper->escapeHtml('sample'); ?>
                            </a>
                        <?php } ?>
                        <?php if ($_linksPurchasedSeparately) { ?>
                            <?= /* @noEscape */ 
                            $block->getLinkPrice($_link, $productId); ?>
                        <?php } ?>
                    </label>
                </div>
            <?php } ?>
            <?php if ($_linksPurchasedSeparately && $_linksLength > 1) { ?>
                <div class="field choice downloads-all">
                    <input type="checkbox"
                           data-notchecked="<?= $escaper->escapeHtml('Select all'); ?>"
                           data-checked="<?= $escaper->escapeHtml('Unselect all'); ?>"
                           id="links_all"/>
                    <label class="label" for="links_all"><span><?= $escaper->escapeHtml('Select all'); ?></span></label>
                </div>
            <?php } ?>
        </div>
        <?php if ($_isRequired) { ?>
            <span id="links-advice-container"></span>
        <?php } ?>
    </div>
<?php } ?>
