<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template.
 *
 * @var \Magento\Catalog\Block\Product\ListProduct $block
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
?>
<?php if (!$_productCollection->count()) { ?>
    <div class="message info empty">
        <div><?php echo // @escapeNotVerified
            __('We can\'t find products matching the selection.'); ?></div>
    </div>
<?php } else { ?>
    <?php echo $block->getToolbarHtml(); ?>
    <?php echo $block->getAdditionalHtml(); ?>
    <?php
    if ('grid' == $block->getMode()) {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }

    /**
     * Position for actions regarding image size changing in vde if needed.
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php echo // @escapeNotVerified
    $viewMode; ?> products-<?php echo // @escapeNotVerified
    $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var \Magento\Catalog\Model\Product $_product */ ?>
            <?php foreach ($_productCollection as $_product) { ?>
                <?php echo // @escapeNotVerified
                (1 == $iterator++) ? '<li class="item product product-item">' : '</li><li class="item product product-item">'; ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if (null != $pos) {
                        $position = ' style="left:'.$productImage->getWidth().'px;'
                            .'top:'.$productImage->getHeight().'px;"';
                    }
                    ?>
                    <?php // Product Image?>
                    <a href="<?php echo // @escapeNotVerified
                    $_product->getProductUrl(); ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php echo // @escapeNotVerified
                               $_product->getProductUrl(); ?>">
                                <?php echo // @escapeNotVerified
                                $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php echo // @escapeNotVerified
                        $block->getProductPrice($_product); ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos((string) $pos, (string) $viewMode.'-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos((string) $pos, (string) $viewMode.'-primary') ? $position : ''; ?>>
                                    <?php if ($_product->isSaleable()) { ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?php echo // @NoEscape
                                        $_product->getSku(); ?>" action="<?php echo // @NoEscape
                                        $postParams['action']; ?>" method="post">
                                            <input type="hidden" name="product" value="<?php echo // @escapeNotVerified
                                            $postParams['data']['product']; ?>">
                                            <input type="hidden" name="<?php echo // @escapeNotVerified
                                            Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php echo // @escapeNotVerified
                                            $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                            <?php echo $block->getBlockHtml('formkey'); ?>
                                            <?php if ('no' == $_product->getData('subscription_configurate')
                                                || is_null($_product->getData('subscription_configurate'))) { ?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php echo // @escapeNotVerified
                                                        __('Add to Cart'); ?></span>
                                                </button>
                                            <?php } else { ?>
                                                <a class="action tocart primary"
                                                   href="<?php echo $subHelper->getProductDetailUrl($_product->getId()); ?>">
                                                    <span><?php echo // @escapeNotVerified
                                                        __('View Details'); ?></span>
                                                </a>
                                            <?php } ?>
                                        </form>
                                    <?php } else { ?>
                                        <?php if ($_product->isAvailable()) { ?>
                                            <div class="stock available"><span><?php echo // @escapeNotVerified
                                                    __('In stock'); ?></span></div>
                                        <?php } else { ?>
                                            <div class="stock unavailable"><span><?php echo // @escapeNotVerified
                                                    __('Out of stock'); ?></span></div>
                                        <?php } ?>
                                    <?php } ?>
                                </div>
                                <div data-role="add-to-links"
                                     class="actions-secondary"<?php echo strpos((string) $pos, (string) $viewMode.'-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')) { ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php } ?>
                                </div>
                            </div>
                            <?php if ($showDescription) { ?>
                                <div class="product description product-item-description">
                                    <?php echo // @escapeNotVerified
                                    $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description'); ?>
                                    <a href="<?php echo // @escapeNotVerified
                                    $_product->getProductUrl(); ?>" title="<?php echo // @escapeNotVerified
                                    $_productNameStripped; ?>"
                                       class="action more"><?php echo // @escapeNotVerified
                                        __('Learn More'); ?></a>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                </div>
                <?php echo ($iterator == count($_productCollection) + 1) ? '</li>' : ''; ?>
            <?php } ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml(); ?>
    <?php if (!$block->isRedirectToCartEnabled()) { ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?php echo // @NoEscape
            $_product->getSku(); ?>"
                }
            }
        }

        </script>
    <?php } ?>
<?php } ?>
