<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php $_order = $block->getOrder(); ?>
<?php $subProductId = $_order->getSubProductId(); ?>
<?php if ($_order) { ?>
    <?php $_items = $_order->getAllItems(); ?>
    <table class="email-items">
        <thead>
        <tr>
            <th class="item-info">
                <?php echo /* @escapeNotVerified */ __('Items'); ?>
            </th>
            <th class="item-qty">
                <?php echo /* @escapeNotVerified */ __('Qty'); ?>
            </th>
            <th class="item-price">
                <?php echo /* @escapeNotVerified */ __('Price'); ?>
            </th>
        </tr>
        </thead>
        <?php foreach ($_items as $_item) { ?>
            <?php
            $productId = $_item->getProductId();
            if ($subProductId == $productId) {
                ?>
                <?php if (!$_item->getParentItem()) { ?>
                    <tbody>
                    <?php echo $block->getItemHtml($_item); ?>
                    </tbody>
                <?php } ?>
            <?php
            } ?>
        <?php } ?>
        <tfoot class="order-totals">
        </tfoot>
    </table>
    <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order', $_order, $_order->getStore()) && $_order->getGiftMessageId()) { ?>
        <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessage($_order->getGiftMessageId()); ?>
        <?php if ($_giftMessage) { ?>
            <br />
            <table class="message-gift">
                <tr>
                    <td>
                        <h3><?php echo /* @escapeNotVerified */ __('Gift Message for this Order'); ?></h3>
                        <strong><?php echo /* @escapeNotVerified */ __('From:'); ?></strong> <?php echo $block->escapeHtml($_giftMessage->getSender()); ?>
                        <br /><strong><?php echo /* @escapeNotVerified */ __('To:'); ?></strong> <?php echo $block->escapeHtml($_giftMessage->getRecipient()); ?>
                        <br /><strong><?php echo /* @escapeNotVerified */ __('Message:'); ?></strong>
                        <br /><?php echo $block->escapeHtml($_giftMessage->getMessage()); ?>
                    </td>
                </tr>
            </table>
        <?php } ?>
    <?php } ?>
<?php } ?>
