<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */

/** @var \Magento\Wishlist\Model\Item $item */
/** @var \Magento\Framework\Escaper $escaper */

$item = $block->getItem();
$product = $item->getProduct();
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
?>
<?php foreach ($block->getChildNames() as $childName) { ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false); ?>
<?php } ?>
<div class="box-tocart">
    <fieldset class="fieldset">
        <?php if ($item->canHaveQty() && $product->isVisibleInSiteVisibility()) { ?>
            <?php if ('subscription_only' !== $product->getData('subscription_configurate')) { ?>
                <div class="field qty">
                    <label class="label"
                           for="qty[<?= $escaper->escapeHtml($item->getId()); ?>]"><span><?= $escaper->escapeHtml('Qty'); ?></span></label>
                    <div class="control">
                        <input type="number" data-role="qty" id="qty[<?php echo $block->escapeHtmlAttr($item->getId()); ?>]"
                               class="input-text qty"
                               data-validate="{'required-number':true,'validate-greater-than-zero':true}"
                               name="qty[<?= /* @noEscape */  $block->escapeHtmlAttr($item->getId()); ?>]" value="<?php echo // @noEscape
                        (int) ($block->getAddToCartQty($item) * 1); ?>">
                    </div>
                </div>
            <?php } ?>
        <?php } ?>
        <?php if ($product->isSaleable()) { ?>

            <?php if ('no' == $product->getData('subscription_configurate')
                || is_null($product->getData('subscription_configurate'))) { ?>
                <div class="product-item-actions">
                    <div class="actions-primary">
                        <button type="button" data-role="tocart" data-post='<?= /* @noEscape */ $block->getItemAddToCartParams($item); ?>'
                                title="<?= $escaper->escapeHtml('Add to Cart'); ?>"
                                data-item-id="<?php echo $block->escapeHtmlAttr($item->getId()); ?>"
                                class="action tocart primary">
                            <span><?= $escaper->escapeHtml('Add to Cart'); ?></span>
                        </button>
                    </div>
                </div>

            <?php } else { ?>
                <a class="action tocart primary" href="<?= /* @noEscape */ $subHelper->getProductDetailUrl($product->getId()); ?>">
                    <span><?= $escaper->escapeHtml('View Details'); ?></span>
                </a>
            <?php } ?>

        <?php } else { ?>
            <?php if ($product->getIsSalable()) { ?>
                <p class="available stock" title="<?= $escaper->escapeHtml('Availability'); ?>">
                    <span><?= $escaper->escapeHtml('In stock'); ?></span>
                </p>
            <?php } else { ?>
                <p class="unavailable stock" title="<?php echo $escaper->escapeHtmlAttr('Availability'); ?>">
                    <span><?= $escaper->escapeHtml('Out of stock'); ?></span>
                </p>
            <?php } ?>
        <?php } ?>
    </fieldset>
</div>
