<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Comment $block */

/* @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();

?>
<?php if ($product->getData('subscription_configurate') !== 'subscription_only') : ?>

    <div class="field comment-box">
        <label class="label" for="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>">
            <span><?= $block->escapeHtml(__('Comment')) ?></span>
        </label>
        <div class="control">
            <textarea id="product-item-comment-<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>"
                      placeholder="<?= /* @noEscape */
                      $this->helper('Magento\Wishlist\Helper\Data')->defaultCommentString() ?>"
                      name="description[<?= $block->escapeHtmlAttr($item->getWishlistItemId()) ?>]"
                      title="<?= $block->escapeHtmlAttr(__('Comment')) ?>"
                      class="product-item-comment"><?= ($block->escapeHtml($item->getDescription())) ?></textarea>
        </div>
    </div>
<?php endif; ?>
