<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Catalog\Block\Product\View $block */
/** @var \Magento\Framework\Escaper $escaper */
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = $escaper->escapeHtml('Add to Cart'); ?>
<?php if ($_product->isSaleable()) { ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) { ?>
                <?php if ('subscription_only' !== $_product->getData('subscription_configurate')) { ?>
                    <div class="field qty">
                        <label class="label" for="qty"><span><?=
                                $escaper->escapeHtml('Qty'); ?></span></label>
                        <div class="control">
                            <input type="number"
                                   name="qty"
                                   id="qty"
                                   value="<?= // @noEscape
                                   $block->getProductDefaultQty() * 1; ?>"
                                   title="<?= // @noEscape
                                   __('Qty'); ?>"
                                   class="input-text qty"
                                   data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())); ?>"
                            />
                        </div>
                    </div>
                <?php } ?>
            <?php } ?>
            <div class="actions">
                <!-- If product is Subscription only -->
                <?php if (('subscription_only' == $_product->getData('subscription_configurate')
                        || 'optional' == $_product->getData('subscription_configurate'))
                    && !(is_null($_product->getData('subscription_attribute_product')))) { ?>
                    <div class="field subscription">
                        <input <?php if ($subHelper->getProductSubscribed($_product->getId())) { ?>
                            checked="checked"<?php } ?>
                                type="checkbox" id="subscriptionPopup" data-bind="scope:'subscriptionPopup'"
                                data-role="subscriptionPopup" class="subscriptionPopup"
                                title="<?= $block->escapeHtmlAttr(__('Subscribe')); ?>" class="checkbox"/>
                        <label class="label" for="subscriptionPopup">
                    <span>
                        <?php $label = $subHelper->getProductOptionLabel(); ?>
                        <?php if (is_null($label)) { ?>
                            <?= $escaper->escapeHtml('Subscription'); ?>
                        <?php } else { ?>
                            <?= /* @noEscape */ $subHelper->getProductOptionLabel(); ?>
                        <?php }?>

                    </span>
                        </label>
                    </div>
                <?php } ?>

                <?php if ('no' == $_product->getData('subscription_configurate')
                    || 'optional' == $_product->getData('subscription_configurate')
                    || is_null($_product->getData('subscription_configurate'))) { ?>
                    <button type="submit"
                            title="<?=  /* @noEscape */
                            $buttonTitle; ?>"
                            class="action primary tocart"
                            id="product-addtocart-button">
                        <span><?= /* @noEscape */
                            $buttonTitle; ?></span>
                    </button>
                <?php } ?>
                <?=  /* @noEscape */ $block->getChildHtml('', true); ?>

            </div>
        </div>
    </div>
    <div id="popup-mpdal" style="display: none;">
        <h1>hello world</h1>
    </div>
<?php } ?>
<?php if ($block->isRedirectToCartEnabled()) { ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }

    </script>
<?php } else { ?>
    <script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }

    </script>
<?php } ?>
