<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var \Magento\Framework\Escaper $escaper */

$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
$subHelperLinks = $this->helper('Wagento\Subscription\Helper\Product');
?>
<?php if ($block->isProductVisibleInSiteVisibility()) { ?>
    <?php
    $itemId = $block->getItem()->getId();
    $productId = $block->getItem()->getProductId();
    $isSubscribed = $block->getItem()->getIsSubscribed();
    $actionSubscription = ($isSubscribed) ? 'Unsubscribe' : 'Subscribe';
    $productType = $subHelper->getProductType($productId);
    ?>
    <!-- Show Subscription popup Only for non subscription Items-->
    <?php $subscriptionOptions = $subHelper->getSubscriptionConfigurations($productId); ?>
    <?php if ('optional' == $subscriptionOptions || 'subscription_only' == $subscriptionOptions) { ?>
        <?php // if(!$isSubscribed):?>
        <div class="field subscription">
            <input type="checkbox" id="subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>"
                   data-bind="scope: subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>"
                   data-role="subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>"
                   class="subscriptionPopup<?= $escaper->escapeHtml($itemId); ?> subscriptionPopup<?= $escaper->escapeHtml($actionSubscription); ?><?= $escaper->escapeHtml($itemId); ?>"
                   title="<?= $escaper->escapeHtml($subHelper->getProductOptionLabel()); ?>" class="checkbox"
                   <?php if ($isSubscribed) { ?> checked="checked" <?php } ?>
            >
            <label class="label" for="product_subscription">
                <span>
                    <!--get label value from system configurations -->
                    <?= /* @noEscape */ $subHelper->getProductOptionLabel(); ?>
                </span>
            </label>
        </div>
        <?php $subId = $subHelper->getSubscriptionId($productId); ?>
        <!-- if subscription plan assigned start -->
        <?php if (isset($subId)) { ?>
            <?php
            $priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
            $fee = $priceHelper->currency(number_format($subHelper->getSubFee($subId), 2), true, false);
            $discount = $priceHelper->currency(number_format($subHelper->getSubscriptionDiscount($subId), 2), true, false);
            $_linksPurchasedSeparately = $subHelperLinks->getLinksPurchasedSeparately($productId);
            $isSaleable = $subHelperLinks->getProduct($productId)->isSaleable();
            $hasLinks = $subHelperLinks->hasLinks($productId);
            $getLinksTitle = $subHelperLinks->getLinksTitle($productId);
            $_isRequired = $subHelperLinks->getLinkSelectionRequired($productId);
            $_links = $subHelperLinks->getLinks($productId);
            ?>
            <div id="subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>" data-bind="scope:'subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>'"
                 data-role="subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>" class="subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>">

                <!-- ko template: getTemplate() --><!-- /ko -->
                <script type="text/x-magento-init">
                {
                    "#subscriptionPopup<?=$escaper->escapeHtml($itemId);?>": {
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "subscriptionPopup<?= $escaper->escapeHtml($itemId); ?>": {
                                    "component": "Wagento_Subscription/js/view/subscription-popup-cart",
                                    "isVisible": true,
                                    "subsname": "<?=$escaper->escapeHtml( $subHelper->getSubName($subId)); ?>",
                                    "frequency": "<?= $escaper->escapeHtml($subHelper->getSubFrequency($subId)); ?>",
                                    "discountWithoutCurrency": "<?= $escaper->escapeHtml($subHelper->getSubscriptionDiscount($subId)); ?>",
                                    "discount": "<?=$escaper->escapeHtml($discount); ?>",
                                    "cost": "<?=$escaper->escapeHtml($fee); ?>",
                                    "costWithoutCurrency": "<?= $escaper->escapeHtml($subHelper->getSubFee($subId)); ?>",
                                    "subscriptionId" : "<?= $escaper->escapeHtml($subHelper->getSubscriptionId($productId)); ?>",
                                    "state": "<?= $escaper->escapeHtml($actionSubscription); ?>",
                                    "productId" : "<?= $escaper->escapeHtml($productId); ?>",
                                    "itemId":"<?= $escaper->escapeHtml($itemId); ?>",
                                    "howMany" : "<?= $escaper->escapeHtml($subHelper->getDefaultSubscriptionHowMany($subId)); ?>",
                                    "isEnableHowMany" : "<?= $escaper->escapeHtml($subHelper->isSubscriptionEnableHowMany()); ?>",
                                    "howManyUnit": "<?= $escaper->escapeHtml($subHelper->getHowManyUnits($subId)); ?>",
                                    "linksPurchasedSeparately" : "<?= $escaper->escapeHtml($_linksPurchasedSeparately); ?>",
                                    "isSaleable" : "<?= $escaper->escapeHtml($isSaleable); ?>",
                                    "hasLinks" : "<?= $escaper->escapeHtml($hasLinks); ?>",
                                    "linksTitle" : "<?= $escaper->escapeHtml($getLinksTitle); ?>",
                                    "isRequired" : "<?= $escaper->escapeHtml($_isRequired); ?>",
                                    "links" : <?= $escaper->escapeHtml($subHelper->getJsonEncode($subHelperLinks->getLinks($productId))); ?>
                                }
                            }
                        }
                    }
                }

                </script>
            </div>
        <?php } ?>
        <!-- if subscription plan assigned End -->
    <?php } ?>
<?php } ?>
