<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

/**@var $block \Wagento\Subscription\Block\Frontend\Product\Popup */
$fee = '';
$discount = '';
?>
<?php if (!empty($fee)): ?>
    <?php
         $fee = $block->getFormattedPrice(number_format( $block->getSubscriptionFee(), 2)); //phpcs:ignore
    ?>
<?php endif; ?>

<?php if (!empty($discount)): ?>
    <?php $discount = $block->getFormattedPrice(number_format($block->getSubscriptionDiscount(), 2)); ?>
<?php endif; ?>

<?php
$productId = $block->getProductId();
$isInCart = $block->getProductInCart($productId);
?>
<div id="subscriptionPopup" data-bind="scope:'subscriptionPopup'" data-role="subscriptionPopup"
     class="subscriptionPopup">

    <div class="block-subscription"
         data-bind="afterRender: setModalElement"
         style="display: none">

        <!-- ko if: isInCart == "0" -->
        <div class="popup-authentication">
            <div class="block block-new-customer">
                <div class="block-title">
                    <strong id="block-new-customer-heading"
                            role="heading"
                            aria-level="2"
                            data-bind="i18n: 'Subscriptions Options'"></strong>
                </div>
                <div class="block-content">
                    <div>
                        <div class="field subscription-name">
                            <span data-bind="i18n: 'Name:'"></span>
                            <span data-bind="text: subscriptionName"></span>
                        </div>

                        <div class="field subscription-frequency">
                            <span data-bind="i18n: 'Frequency:'"></span>
                            <span data-bind="text: subscriptionFrequency"></span>
                        </div>

                        <!-- ko if: isEnableHowMany == "0" -->
                        <!-- ko if: howMany != "0" && howMany != ""-->
                        <div class="field subscription-howmany">
                            <span data-bind="i18n: 'Subscription Cycles:'"></span>
                            <span data-bind="text: howMany"></span>
                            <span data-bind="text: howManyUnit"></span>
                        </div>
                        <!--/ko-->
                        <!--/ko-->

                        <div class="field subscription-discount">
                            <span data-bind="i18n: 'Discount:'"></span>
                            <span data-bind="text: subscriptionDiscount"></span>
                        </div>

                        <!-- ko if: costWithoutCurrency != "0.0000" -->
                        <div class="field subscription-fee">
                            <span data-bind="i18n: 'Fee:'"></span>
                            <span data-bind="text: subscriptionFee"></span>
                        </div>
                        <!--/ko-->

                    </div>
                </div>
            </div>
            <div class="block">
                <div class="block-title">
                    <strong role="heading"
                            aria-level="2"
                            data-bind="i18n: 'Subscription Detail'"></strong>
                </div>
                <br/>
                <div class="block-content">
                    <form class="form form-subscription"
                          method="post"
                          data-bind="event: {submit: subscribe }"
                          id="subscription-form">
                        <div class="fieldset login">

                            <div class="field subscription-howmany required">
                                <!-- ko if: isEnableHowMany == "1" -->
                                <span data-bind="i18n: 'Enter Subscription Cycle Number'"></span><em> * </em>
                                <div class="control">
                                    <input type="number"
                                           name="subHowMany"
                                           id="how_many"
                                           value=""
                                           title="<?= /* @escapeNotVerified */ __('Enter Nymber of Cycles you would like to subscribe') //phpcs:ignore ?>"
                                           class="input-text howmany"
                                           data-validate="{'required-number':true,digits:true}"
                                           data-bind="value: subHowMany"/>
                                </div>
                                <!-- /ko -->

                                <div class="field subscription-qty required">
                                    <span data-bind="i18n: 'Qty'"></span><em> *</em>
                                    <div class="control">
                                        <input type="number"
                                               name="subqty"
                                               id="sub_qty"
                                               value=""
                                               title="<?= /* @escapeNotVerified */ __('Subscription Qty') //phpcs:ignore ?>"
                                               class="input-text sub_qty"
                                               data-validate="{'required':true, 'pattern':/^\d+(\.\d{1,2})?$/, 'validate-greater-than-zero':true}" <?php //phpcs:ignore ?>
                                               data-bind="value: subqty"/>
                                    </div>

                                </div>
                                <input id="subscriptionProductId" name="productId" type="hidden"
                                       data-bind="value:subscriptionProductId"/>
                                <input id="subSubscription" name="subSubscription" type="hidden"
                                       data-bind="value: subSubscription"/>
                                <input id="isEnableHowMany" name="isEnableHowMany" type="hidden"
                                       data-bind="value: isEnableHowMany"/>
                                <input id="howMany" name="howMany" type="hidden" data-bind="value: howMany"/>
                            </div>
                            <?php $type = $block->getProductType(); ?>
                            <?php if ($type == 'downloadable'): ?>
                                <div id="product-options-wrapper-popup" class="product-options-wrapper-popup"></div>
                            <?php endif; ?>
                            <div class="actions-toolbar">
                                <div class="primary">
                                    <button type="submit" class="action action-subscribe secondary"
                                            name="send" id="save-subscribe">
                                        <span data-bind="i18n: 'Subscribe'"></span>
                                    </button>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <!--/ko-->

        <!-- ko if: isInCart == "1" -->
        <form class="form unsubscription-form" method="post" data-bind="event: {submit: unsubscribe }"
              id="unsubscription-form">
            <div class="content unsuscription alert">
                <div class="content">
                    <p class="content" data-bind="i18n: 'Are you sure, you want to unsubscribe this product?'"></p>
                </div>
                <input id="un_product_id" name="product_id" type="hidden" data-bind="value:subscriptionProductId"/>
                <div class="actions-toolbar">
                    <div class="primary">
                        <button type="submit" class="action action-unsubscribe secondary action delete"
                                name="unsubscribe" id="unsubscribe"
                                data-bind="attr: {'data-cart-item': subscriptionProductId, title: $t('Remove item')}"
                        >
                            <span data-bind="i18n: 'Unsubscribe'"></span>
                        </button>
                    </div>
                </div>
            </div>
        </form>
        <!--/ko-->
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#subscriptionPopup": {
                "Magento_Ui/js/core/app": {
                    "components": {
                        "subscriptionPopup": {
                            "component": "Wagento_Subscription/js/view/subscription-popup",
                            "isVisible": true,
                            "isInCart": "<?=  /* @noEscape */  $isInCart ?>",
                            "subsname": "<?=  /* @noEscape */  $block->getSubscriptionName() ?>",
                            "frequency": "<?=  /* @noEscape */  $block->getSubscriptionFrequency() ?>",
                            "discountWithoutCurrency": "<?=  /* @noEscape */  $block->getSubscriptionDiscount() ?>",
                            "discount": "<?=  /* @noEscape */  $discount ?>",
                            "cost": "<?= /* @noEscape */ $fee ?>",
                            "costWithoutCurrency": "<?= /* @noEscape */  $block->getSubscriptionFee() ?>",
                            "subscriptionId" : "<?= /* @noEscape */  $block->getSubscriptionId() ?>",
                            "productId" : "<?=  /* @noEscape */  $block->getProductId() ?>",
                            "howMany" : "<?=  /* @noEscape */  $block->getSubscriptionHowMany() ?>",
                            "isEnableHowMany" : "<?=  /* @noEscape */  $block->isEnableHowMany() ?>",
                            "howManyUnit": "<?=  /* @noEscape */  $block->getHowManyUnit() ?>"
                        }
                    }
                }
            }
        }

    </script>
</div>
