<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var Wagento\Subscription\Block\Adminhtml\Subscription\ProductGrid $block */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml(); ?>
<input type="hidden" name="category_products" id="in_category_products" data-form-part="subscription_form" value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Wagento_Subscription/products/assign-products": {
                "selectedProducts": <?=  /* @noEscape */   $block->getProductsJson(); ?>,
                "gridJsObjectName": <?=  /* @noEscape */  '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }

</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
