<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php echo $block->getGridHtml(); ?>
<input type="hidden" name="category_products" id="in_category_products" data-form-part="subscription_form" value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Wagento_Subscription/products/assign-products": {
                "selectedProducts": <?php /* @escapeNotVerified */
                echo $block->getProductsJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */
                echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }

</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    require('mage/apply/main').apply();
</script>
