<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @var \Wagento\Subscription\Block\Adminhtml\Sales\Subscription\View\CustomerDetails $block
?>
<?php $subDetails = $block->getSubscriptionDetail(); ?>

<?php $getCreatedAt = $subDetails->getCreatedAt();
$date = new DateTime($getCreatedAt);
$subAdminDate = $date->format('F d, Y h:i:s');

$getLastRenewed = $subDetails->getLastRenewed();
$dateLastRenew = new DateTime($getLastRenewed);
$subLastRenewedDate = $dateLastRenew->format('F d, Y h:i:s');

$subHelper = $this->helper('Wagento\Subscription\Helper\Data');
$priceHelper = $this->helper('Magento\Framework\Pricing\Helper\Data');

?>
<section class="admin__page-section order-view-account-information sales-subscription">
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information sales-subscription">
            <?php /* Subscription Sales Order Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                        <?php echo $block->escapeHtml(__('Subscription Profile # %1', $subDetails->getId())); ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table sales-subscription">
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Subscription Plan name')); ?></th>
                        <td><?php echo $block->escapeHtml($subDetails->getSubName()); ?></td>
                    </tr>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Subscription Status')); ?></th>
                        <td>
                            <span id="subscription_status"><?php echo $subHelper->getSubscriptionStatus($subDetails->getStatus()); ?></span>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Subscription Frequency')); ?></th>
                        <td>
                            <?php echo $block->escapeHtml($subHelper->getSubscriptionFrequency($subDetails->getSubFrequency())); ?>
                            <?php if (null != $subDetails->getHowMany()) { ?>
                                <?php echo ' - '; ?>
                                <?php echo $subDetails->getHowMany(); ?>
                                <?php echo $block->escapeHtml($subHelper->getHowManyUnits($subDetails->getFrequency())); ?>
                            <?php } ?>
                        </td>
                    </tr>

                    <tr>
                        <th><?php echo $block->escapeHtml(__('Subscription Started Date')); ?></th>
                        <td><?php echo $block->escapeHtml($subAdminDate); ?></td>
                    </tr>

                    <tr>
                        <th><?php echo $block->escapeHtml(__('Last Renewed')); ?></th>
                        <td><?php echo $block->escapeHtml($subLastRenewedDate); ?></td>
                    </tr>
                </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information sales-subscription">
            <?php /* Account Information */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Customer Information')); ?></span>
                <div class="actions">
                    <?php if ($customerUrl = $block->getCustomerViewUrl($subDetails->getCustomerId())) { ?>
                        <a href="<?php echo // @noEscape
                        $block->getCustomerViewUrl($subDetails->getCustomerId()); ?>" target="_blank">
                            <?php echo $block->escapeHtml(__('Edit Customer')); ?>
                        </a>
                    <?php } ?>
                </div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table sales-subscription">
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Customer Name')); ?></th>
                        <td>
                            <?php if ($customerUrl = $block->getCustomerViewUrl($subDetails->getCustomerId())) { ?>
                                <a href="<?php echo $block->escapeUrl($customerUrl); ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($subDetails->getCustomerName()); ?></span>
                                </a>
                            <?php } else { ?>
                                <?php echo $block->escapeHtml($subDetails->getCustomerName()); ?>
                            <?php } ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Email')); ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($subDetails->getEmail()); ?>">
                                <?php echo $block->escapeHtml($subDetails->getEmail()); ?></a></td>
                    </tr>
                    <tr>
                        <th><?php echo $block->escapeHtml(__('Subscription Billing Count')); ?></th>
                        <td><?php echo $block->escapeHtml($subDetails->getBillingCount()); ?></td>

                    </tr>
                    <?php if (false == $block->isSingleStoreMode()) { ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__('Purchased From')); ?></th>
                            <td><?php echo $block->escapeHtml($block->getSubscriptionStoreName($subDetails->getStoreId()), ['br']); ?></td>
                        </tr>
                    <?php } ?>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('Subscription Address Information')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Billing Address')); ?></span>
                <div class="actions"></div>
            </div>
            <address class="admin__page-section-item-content"><?php echo // @noEscape
                $block->getBillingAddress($subDetails->getOrderId(), $subDetails->getBillingAddressId()); ?></address>
        </div>
        <?php // if (!$block->getIsVirtual($subDetails->getOrderId())):?>
        <div class="admin__page-section-item order-shipping-address">
            <?php /* Shipping Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Shipping Address')); ?></span>
                <div class="actions"></div>
            </div>
            <address class="admin__page-section-item-content"><?php echo // @noEscape
                $block->getShippingAddress($subDetails->getOrderId(), $subDetails->getShippingAddressId()); ?></address>
        </div>
        <?php // endif;?>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo // @escapeNotVerified
            __('Payment & Shipping Method'); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-payment-method">
            <?php /* Billing Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Payment Information')); ?></span>
                <div class="actions"></div>
            </div>
            <?php $paymentDetail = $block->getPaymentMethod($subDetails->getOrderId(), $subDetails->getPublicHash(), $subDetails->getCustomerId()); ?>
            <div class="box-content">
                <dl class="payment-method">
                    <p><?php echo $paymentDetail['method_title']; ?></p>
                    <?php if (isset($paymentDetail['cc_type'])) { ?>
                        <dd class="content">
                            <strong><?php echo $block->escapeHtml(__('Credit Card Type')); ?></strong>
                            <?php echo $paymentDetail['cc_type']; ?>

                            <br/>
                            <strong><?php echo $block->escapeHtml(__('Credit Card Number')); ?></strong>
                            <?php echo $paymentDetail['cc_number']; ?>
                        </dd>
                    <?php } ?>
                </dl>
            </div>
        </div>
        <div class="admin__page-section-item order-shipping-method">
            <?php /* Shipping Address */ ?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php echo $block->escapeHtml(__('Shipping & Handling Information')); ?></span>
                <div class="actions"></div>
            </div>
            <address>
                <?php $shipping = $block->getShippingMethod($subDetails->getOrderId()); ?>
                <?php if (!empty($shipping)) { ?>
                    <?php echo /* @noEscape */ $shipping; ?>
                    <?php } else { ?>
                    <?php echo $block->escapeHtml(__('N/A')); ?>
                <?php } ?>
            </address>
        </div>
    </div>
</section>

<section class="admin__page-section">
    <div class="admin__page-section-title">
        <span class="title"><?php echo // @escapeNotVerified
            __('Item Subscribed'); ?></span>
    </div>
    <div class="admin__table-wrapper">
        <table class="data-table admin__table-primary edit-order-table">
            <thead>
            <tr class="headings">
                <th><?php echo __('Product'); ?></th>
                <th><?php echo __('Original Price'); ?></th>
                <th><?php echo __('Price'); ?></th>
                <th><?php echo __('Initial Fee'); ?></th>
                <th><?php echo __('Qty'); ?></th>
                <th><?php echo __('Subtotal'); ?></th>
                <th><?php echo __('Row Total'); ?></th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>
                    <?php echo __($subDetails->getName()); ?><em> </em><br/>
                    <strong><?php echo __('SKU:'); ?></strong><?php echo __($subDetails->getSku()); ?>
                </td>
                <td><?php echo $priceHelper->currency(number_format($subDetails->getOriginalPrice(), 2), true, false); ?></td>
                <td><?php echo $priceHelper->currency(number_format($subDetails->getPrice(), 2), true, false); ?></td>
                <td><?php echo $priceHelper->currency(number_format($subDetails->getSubFee(), 2), true, false); ?></td>
                <td>
                    <?php echo __('Subscribed'); ?>
                    <?php echo (int) $subDetails->getQtyOrdered(); ?>
                </td>
                <?php $total = ($subDetails->getPrice()) + $subDetails->getShipping(); ?>
                <td><?php echo $priceHelper->currency(number_format($total, 2), true, false); ?></td>
                <td><?php echo $priceHelper->currency(number_format($total, 2), true, false); ?></td>
            </tr>
            </tbody>
        </table>
    </div>
</section>
