<?php
/**
 * Copyright Wagento Creative LLC ©, All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

// @var $block \Magento\Catalog\Block\Product\Compare\ListCompare
$subHelper = $this->helper('Wagento\Subscription\Helper\Data');

?>
<?php $_total = $block->getItems()->getSize(); ?>
<?php if ($_total) { ?>
    <a href="#" class="action print" title="<?php echo // @escapeNotVerified
    __('Print This Page'); ?>">
        <span><?php echo // @escapeNotVerified
            __('Print This Page'); ?></span>
    </a>
    <div class="table-wrapper comparison">
        <table class="data table table-comparison" id="product-comparison"
               data-mage-init='{"compareList":{
                    "windowPrintSelector":".action.print",
                    "productsInRow":"5",
                    "selectors":{
                        "productAddToCartSelector":"button.action.tocart"}
                }}'>
            <caption class="table-caption"><?php echo // @escapeNotVerified
                __('Compare Products'); ?></caption>
            <thead>
            <tr>
                <?php $_i = 0; ?>
                <?php foreach ($block->getItems() as $_item) { ?>
                    <?php if (0 == $_i++) { ?>
                        <th scope="row" class="cell label remove"><span><?php echo // @escapeNotVerified
                                __('Remove Product'); ?></span></th>
                    <?php } ?>
                    <td class="cell remove product">
                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                        <a href="#" data-post='<?php echo // @escapeNotVerified
                        $compareHelper->getPostDataRemove($_item); ?>'
                           class="action delete" title="<?php echo // @escapeNotVerified
                        __('Remove Product'); ?>">
                            <span><?php echo // @escapeNotVerified
                                __('Remove Product'); ?></span>
                        </a>
                    </td>
                <?php } ?>
            </tr>
            </thead>
            <tbody>
            <tr>
                <?php $_i = 0; ?>
                <?php $_helper = $this->helper('Magento\Catalog\Helper\Output'); ?>
                <?php /** @var \Magento\Catalog\Model\Product $_item */ ?>
                <?php foreach ($block->getItems() as $_item) { ?>
                    <?php if (0 == $_i++) { ?>
                        <th scope="row" class="cell label product"><span><?php echo // @escapeNotVerified
                                __('Product'); ?></span></th>
                    <?php } ?>
                    <td data-th="<?php echo $block->escapeHtml(__('Product')); ?>" class="cell product info">
                        <a class="product-item-photo" href="<?php echo // @escapeNotVerified
                        $block->getProductUrl($_item); ?>" title="<?php echo // @escapeNotVerified
                        $block->stripTags($_item->getName(), null, true); ?>">
                            <?php echo $block->getImage($_item, 'product_comparison_list')->toHtml(); ?>
                        </a>
                        <strong class="product-item-name">
                            <a href="<?php echo // @escapeNotVerified
                            $block->getProductUrl($_item); ?>" title="<?php echo // @escapeNotVerified
                            $block->stripTags($_item->getName(), null, true); ?>">
                                <?php echo // @escapeNotVerified
                                $_helper->productAttribute($_item, $_item->getName(), 'name'); ?>
                            </a>
                        </strong>
                        <?php echo $block->getReviewsSummaryHtml($_item, 'short'); ?>
                        <?php echo // @escapeNotVerified
                        $block->getProductPrice($_item, '-compare-list-top'); ?>
                        <div class="product-item-actions">
                            <div class="actions-primary">
                                <?php if ($_item->isSaleable()) { ?>
                                    <form data-role="tocart-form" action="<?php echo // @escapeNotVerified
                                    $this->helper('Magento\Catalog\Helper\Product\Compare')->getAddToCartUrl($_item); ?>"
                                          method="post">
                                        <?php echo $block->getBlockHtml('formkey'); ?>
                                        <!-- Subscription View -->
                                        <?php
                                        $subConfig = $_item->getCustomAttribute('subscription_configurate')->getValue();
                                        ?>
                                        <?php if ('no' == $subConfig || is_null('subscription_configurate' == $subConfig)) { ?>
                                            <button type="submit"
                                                    title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                    class="action tocart primary">
                                                <span><?php echo // @escapeNotVerified
                                                    __('Add to Cart'); ?></span>
                                            </button>
                                        <?php } else { ?>
                                            <a class="action tocart primary"
                                               href="<?php echo $subHelper->getProductDetailUrl($_item->getId()); ?>">
                                                <span><?php echo // @escapeNotVerified
                                                    __('View Details'); ?></span>
                                            </a>
                                        <?php } ?>
                                    </form>
                                <?php } else { ?>
                                    <?php if ($_item->getIsSalable()) { ?>
                                        <div class="stock available"><span><?php echo // @escapeNotVerified
                                                __('In stock'); ?></span></div>
                                    <?php } else { ?>
                                        <div class="stock unavailable"><span><?php echo // @escapeNotVerified
                                                __('Out of stock'); ?></span></div>
                                    <?php } ?>
                                <?php } ?>
                            </div>
                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) { ?>
                                <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                    <a href="#" data-post='<?php echo // @escapeNotVerified
                                    $block->getAddToWishlistParams($_item); ?>' class="action towishlist"
                                       data-action="add-to-wishlist">
                                        <span><?php echo // @escapeNotVerified
                                            __('Add to Wish List'); ?></span>
                                    </a>
                                </div>
                            <?php } ?>
                        </div>
                    </td>
                <?php } ?>
            </tr>
            </tbody>
            <tbody>
            <?php foreach ($block->getAttributes() as $_attribute) { ?>
                <tr>
                    <?php $_i = 0; ?>
                    <?php foreach ($block->getItems() as $_item) { ?>
                        <?php if (0 == $_i++) { ?>
                            <th scope="row" class="cell label">
                                    <span class="attribute label">
                                        <?php echo $block->escapeHtml($_attribute->getStoreLabel() ? $_attribute->getStoreLabel() : __($_attribute->getFrontendLabel())); ?>
                                    </span>
                            </th>
                        <?php } ?>
                        <td class="cell product attribute">
                            <div class="attribute value">
                                <?php switch ($_attribute->getAttributeCode()) {
                                    case 'price': ?>
                                        <?php
                                        // @escapeNotVerified
                                        echo $block->getProductPrice(
                                            $_item,
                                            '-compare-list-'.$_attribute->getCode()
                                        );
                                        ?>
                                        <?php break;

                                    case 'small_image': ?>
                                        <?php $block->getImage($_item, 'product_small_image')->toHtml(); ?>
                                        <?php break;

                                    default: ?>
                                        <?php echo // @escapeNotVerified
                                        $_helper->productAttribute($_item, $block->getProductAttributeValue($_item, $_attribute), $_attribute->getAttributeCode()); ?>
                                        <?php break;
                                } ?>
                            </div>
                        </td>
                    <?php } ?>
                </tr>
            <?php } ?>
            </tbody>
        </table>
    </div>
    <?php if (!$block->isRedirectToCartEnabled()) { ?>
        <script type="text/x-magento-init">
            {
                "[data-role=tocart-form]": {
                    "catalogAddToCart": {}
                }
            }

        </script>
    <?php } ?>
<?php } else { ?>
    <div class="message info empty">
        <div><?php echo // @escapeNotVerified
            __('You have no items to compare.'); ?></div>
    </div>
<?php } ?>
